# Generated by Django 2.0.7 on 2022-07-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isTrash',
            field=models.TextField(default=False),
        ),
    ]
